# Generated by Django 4.2.5 on 2023-09-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_qty',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.PositiveBigIntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('gm', 'gm'), ('liter', 'liter'), ('ml', 'ml'), ('pkt', 'pkt'), ('bunch', 'bunch'), ('dozen', 'dozen'), ('box', 'box'), ('piece', 'piece'), ('inch', 'Inches'), ('cm', 'cm'), ('meter', 'meter'), ('km', 'km')], default='kg', max_length=100),
        ),
    ]
