# Generated by Django 4.2.5 on 2023-09-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
